# ELK Stack image with customization

FROM willdurand/elk

MAINTAINER Jayaram Pradhan <jayaram.pradhan@uimirror.com>

ENV REFRESHED_AT 2015-11-15

COPY logstash-logspout.conf /etc/logstash/logstash-logspout.conf