elk:
  build: elk/
  container_name: uim_elk
  ports:
   - "8081:80"
   - "8082:9200"
  expose:
   - "5000/upd"

logspout:
  build: logspout/
  container_name: uim_logspout
  volumes:
   - "/var/run/docker.sock:/tmp/docker.sock"
  links:
   - elk
  ports:
   - "8083:80"
  environment:
    - ROUTE_URIS=logstash://elk:5000